# Generated by Django 4.1.2 on 2022-10-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('for_le', models.TextField()),
                ('is_current', models.TextField()),
                ('is_deleted', models.TextField()),
                ('name', models.CharField(max_length=255, unique=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'academic_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bcece',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.TextField()),
                ('modified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(max_length=255)),
                ('category_admission', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('father_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('is_le', models.TextField()),
                ('is_reg', models.TextField()),
                ('reg_no', models.BigIntegerField()),
                ('roll_no', models.BigIntegerField()),
                ('student', models.BigIntegerField(blank=True, null=True)),
                ('student_name', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
                ('remarks2', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'bcece',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('is_deleted', models.TextField()),
                ('name', models.CharField(max_length=255, unique=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('short_name', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'institute',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('is_deleted', models.TextField()),
                ('name', models.CharField(max_length=255, unique=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('short_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'program',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeatApproval',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.TextField()),
                ('modified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('approved_filled', models.BigIntegerField(blank=True, null=True)),
                ('approved_seat', models.BigIntegerField(blank=True, null=True)),
                ('handicapped_filled', models.BigIntegerField(blank=True, null=True)),
                ('handicapped_seat', models.BigIntegerField(blank=True, null=True)),
                ('institute', models.BigIntegerField(blank=True, null=True)),
                ('le_filled', models.BigIntegerField(blank=True, null=True)),
                ('le_seat', models.BigIntegerField(blank=True, null=True)),
                ('program', models.BigIntegerField(blank=True, null=True)),
                ('waiver_scheme_filled', models.BigIntegerField(blank=True, null=True)),
                ('waiver_scheme_seat', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'seat_approval',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.TextField()),
                ('modified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=255, null=True)),
                ('admission_type', models.CharField(blank=True, max_length=255, null=True)),
                ('bcece', models.BigIntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('category_admission', models.CharField(blank=True, max_length=255, null=True)),
                ('class_roll_no', models.BigIntegerField(blank=True, null=True)),
                ('comm_city', models.CharField(blank=True, max_length=255, null=True)),
                ('comm_country', models.CharField(blank=True, max_length=255, null=True)),
                ('comm_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('comm_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('comm_pin', models.CharField(blank=True, max_length=6, null=True)),
                ('comm_state', models.CharField(blank=True, max_length=255, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('doj', models.DateField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('father_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('is_iti', models.TextField(blank=True, null=True)),
                ('is_rec', models.TextField()),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=255, null=True)),
                ('perm_city', models.CharField(blank=True, max_length=255, null=True)),
                ('perm_country', models.CharField(blank=True, max_length=255, null=True)),
                ('perm_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('perm_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('perm_pin', models.CharField(blank=True, max_length=6, null=True)),
                ('perm_state', models.CharField(blank=True, max_length=255, null=True)),
                ('reg_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('reg_no', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('student_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_issued', models.TextField(blank=True, null=True)),
                ('is_provisional', models.TextField(blank=True, null=True)),
                ('is_registered', models.IntegerField(blank=True, null=True)),
                ('is_provisnal', models.TextField()),
                ('is_new', models.TextField()),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
    ]
